### ISSUE TITLE
Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by ThomsCass** [Urigo/angular2-meteor#243]
Hi,

I use `"angular2-meteor": "^0.5.3"`

When I want to use `MeteorComponent` in one of my component I get this error : `Uncaught TypeError: Cannot read property 'resolve' of undefined promise.js:16`.

Here is my file

```javascript
import 'reflect-metadata';

import {Component} from 'angular2/core';
import {MeteorComponent} from 'angular2-meteor';

@Component({
    selector: 'user-home',
    templateUrl: 'client/components/dashboard/user/home/user-home.html'
})

export class UserHome extends MeteorComponent {

    constructor() {
        super();
    }
}
```
If I remove the MeteorComponent everything starts to work again.

Am I missing something ?

**Comment by derekkite** [comment]
See #238

**Comment by ThomsCass** [comment]
Is there a solution provide for now or do we have to wait a fix ?

**Comment by MilosStanic** [comment]
I think it has been fixed, but not released yet. I tried installing the fixed angular2-meteor via git clone, but no luck in being able to include it into project. At the bottom of README there is a short explanation how to use git clone.

**Comment by ThomsCass** [comment]
I try to update - go to old version, and now I have everything up to date but the error is still there and what is weird if that even if I remove now MeteorComponent I get the error above. 

So nothing is working for me any more...

**Comment by llnathanll** [comment]
I've noticed that my app breaks with this error at the exact point where I declare RouterLink as a directive in one of my components.  
```
@Component({
  selector: 'some-selector',
  templateUrl: '/client/some/template.html',
  directives: [ RouterLink ]
})
```
If I remove the directive, the app loads without errors.  Of course that means no linking from templates.

**Comment by ThomsCass** [comment]
In the exemple I've shown above there is no `RouterLink`. So for me that's not the reason that breaks the app.

**Comment by ThomsCass** [comment]
here is what to do :

```javascript
"dependencies": {
    "angular2": "^2.0.0-beta.16",
    "angular2-meteor": "https://github.com/Urigo/angular2-meteor",
    "angular2-meteor-auto-bootstrap": "https://github.com/Urigo/angular2-meteor-auto-bootstrap",
    "es6-shim": "^0.35.0",
    "meteor-node-stubs": "^0.2.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "^0.6.10"
  }
```
Becareful there are breaking change in beta 16 : https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

**Comment by barbatus** [comment]
Fixed, dup of https://github.com/Urigo/angular2-meteor/issues/238
