### ISSUE TITLE
Meteor 1.4 compatibility

### ISSUE THREAD

**Issue by jornare** [Urigo/angular2-meteor#372]
Current version of Meteor is 1.4 (as of August 12 2016) and current angular2-meteor (actually the angular2-compilers package) throws a "No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform" error.

**Comment by stefanholzapfel** [comment]
Can't confirm that. 
I'm successfully running Meteor 1.4 (see Screenshot) and those are my dependencies:

`    "@angular/common": "2.0.0-rc.4",`
`    "@angular/compiler": "2.0.0-rc.4",`
`    "@angular/core": "2.0.0-rc.4",`
`    "@angular/forms": "0.2.0",`
`    "@angular/platform-browser": "2.0.0-rc.4",`
`    "@angular/platform-browser-dynamic": "2.0.0-rc.4",`
`    "@angular/router": "3.0.0-beta.2",`
`    "angular2-meteor": "0.6.3-beta.4",`
`    "angular2-meteor-auto-bootstrap": "0.6.0",`
`    "angular2-meteor-polyfills": "0.1.1",`
`    "bootstrap-sass": "3.3.7",`
`    "bootswatch": "3.3.7",`
`    "meteor-node-stubs": "0.2.3",`
`    "ng2-bootstrap": "1.0.24",`
`   "reflect-metadata": "0.1.3",`
`   "rxjs": "5.0.0-beta.10",`
`    "zone.js": "0.6.12"`

![1](https://cloud.githubusercontent.com/assets/9963536/17645397/54e0a59a-61a5-11e6-8cef-a46f06afb652.JPG)

**Comment by stefanholzapfel** [comment]
But you can use "meteor add angular2-compilers@=0.6.0" to install 0.6.0 as a workaround (mind the "="  after @)

**Comment by jornare** [comment]
Thanx @stefanholzapfel. I managed getting stuff up and running by creating a new project and importing all my stuff into it. The first time I tried to update and older package. Even though we got around, I guess the issue is still valid for future updates.

**Comment by bergben** [comment]
Can confirm this issue too, the workaround mentioned by @stefanholzapfel  works fine though as for now.

**Comment by vtulin** [comment]
@bergben This is not a workaround. The question still remains. I guess it sounds like: what is the compatible version of meteor for angular2-compiler@0.6.1. I was trying to downgrade meteor to 1.4.0.1 with no success.
Subscribe.

**Comment by AngelCastilloB** [comment]
I also havent been able to make it work, the work around doesnt work for me. 

I get

> /images-uploader.component.ts (54, 5): Argument of type '{ selector: string; template: string; styleUrls: string[]; viewProviders: typeof DragulaService[]...' is not assignable to parameter of type 'ComponentMetadataType'.
>   Object literal may only specify known properties, and 'directives' does not exist in type 'ComponentMetadataType'.
> client/services/validation.service.ts (21, 10): Module '"node_modules/@angular/common/index"' has no exported member 'ControlGroup'.

**Comment by Tallyb** [comment]
same issue here with 0.6.1. 
Windows 10.

**Comment by barbatus** [comment]
angular2-compilers@0.6.2 should fix it

**Comment by s-bhandari** [comment]
Still getting same issue on Windows 10, meteor 1.4.1.2, node 4.4.6

Also tried using angular2-compilers@0.6.3, no luck.
